package com.su26isc301.backend.enums;

public enum ReportActionType {
    NO_ACTION,
    REJECT_REPORT,
    WARNING,
    HIDE_PRODUCT,
    DISABLE_PROMOTION,
    RESTRICT_LISTING,
    RESTRICT_CHAT,
    REQUIRE_VERIFICATION,
    TEMPORARY_SUSPENSION,
    PERMANENT_BAN,
    RESTORE_PRODUCT,
    RESTORE_PROMOTION,
    REMOVE_RESTRICTION
}
