CREATE TABLE IF NOT EXISTS public.conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE,
    customer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT conversations_vendor_customer_key UNIQUE (vendor_id, customer_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL CHECK (CHAR_LENGTH(TRIM(content)) BETWEEN 1 AND 2000),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_conversations_vendor_updated_at
    ON public.conversations(vendor_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_created_at
    ON public.messages(conversation_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_unread
    ON public.messages(conversation_id, is_read)
    WHERE is_read = FALSE;
